spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql123456
    url: jdbc:mysql://182.92.115.193:3306/bookstore?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB